<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="AWS-PVDI-6" failures="0" tests="2" name="Runner.TestApplication" time="9.102" errors="1" timestamp="2024-01-05T09:47:37 IST" skipped="0">
  <testcase classname="Runner.TestApplication" name="runScenario" time="2.850">
    <error message="Exception occured" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: Exception occured
at stepdefinitions.TestClass.navigate_to_url_feature_two(TestClass.java:13)
at âœ½.navigate to URL feature two(file:///C:/Users/ININDC00076/git/ULS_IjarahAnandh_ULS/AzentioAutomationFramework_AnandhULS/src/test/java/features/snippets/FeatureFile01.feature:5)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestApplication" name="runScenario" time="6.252"/>
</testsuite> <!-- Runner.TestApplication -->
